/*
 * This source file was generated by the Gradle 'init' task
 */
package com.sanvito_damiano.hazelcast;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void Test() {
        Main classUnderTest = new Main();
        assertTrue(classUnderTest != null, "Main class should not be null");
    }
}
